org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.207
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.07.20
mod_id=compactmekanismmachines
mod_name=Compact Mekanism Machines
mod_license=MIT
mod_version=0.2.0
mod_group_id=com.CompactMekanismMachines
mod_authors=nekorobi_0,nanaios
mod_description=Example mod description.\nNewline characters can be used and will be replaced properly.
mekanism_version=1.21.1-10.7.15.81
jei_version=19.22.1.316